### ISSUE TITLE
Sexplib.Conv support for Bytes?

### ISSUE THREAD

**Issue by avsm** [janestreet/sexplib#15]
Right now using `Bytes.t` results in a `Error: Unbound value Bytes.t_of_sexp`.  Would it be possible to add a converter for this to assist with safe-string migration from `String.t_of_sexp`?

**Comment by diml** [comment]
This should be OK. Note that this is not yet released but we added this to `Core_kernel.Std` until we enable safe-string:

```ocaml
type bytes =
  [ `This_type_does_not_equal_string_because_we_want_type_errors_to_say_string ]
```

`Bytes.t` is not diverted though.

**Comment by hhugo** [comment]
should be fixed.
