### ISSUE TITLE
Compilation fails with ocaml 4.03.0+trunk (sexplib.113.00.00)

### ISSUE THREAD

**Issue by smondet** [janestreet/sexplib#17]
```
+ /Users/me/.opam/4.03.0+trunk/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package bigarray -I lib -o lib/conv.cmo lib/conv.ml
File "lib/conv.ml", line 95, characters 12-25:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "lib/conv.ml", line 96, characters 24-43:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "lib/conv.ml", line 187, characters 30-34:
Error: This expression has type Obj.t but an expression was expected of type
         extension_constructor
Command exited with code 2.
```

**Comment by diml** [comment]
Yes, a lot of our code doesn't compile with trunk. Hopefully we should be able to push trunk-following branches soon.

**Comment by avsm** [comment]
@diml any chance of a pull req constraining the appropriate Core packages in OPAM to <4.03.0? would really help with automated testing.

**Comment by diml** [comment]
@avsm, I'll add the constraint to all versions of all JS packages. This error is likely to affect all versions of sexplib and most of our packages depend on it anyway...

**Comment by avsm** [comment]
sounds good to me.

**Comment by dbuenzli** [comment]
A lot of things unfortunately depend on this package. Would it be possible to have a fix and make a new release for 4.03. The same problem reported by @smondet persists.

**Comment by trefis** [comment]
We are currently preparing a new release of our libraries which will work with 4.03.

**Comment by msprotz** [comment]
@trefis if you get a chance to push just a commit that would fix this, that would help with my testing of opam-on-windows + 4.03.0 -- I'm willing to maintain a private repo for testing purposes that would point at the git master revision of sexplib in order to proceed with my testing

**Comment by trefis** [comment]
@msprotz the 4.03 branch already contain such a patch. I'm also hoping to get 4.03 compatible versions of our package into opam soon (cf. https://github.com/ocaml/opam-repository/pull/6094 )

**Comment by msprotz** [comment]
oh excellent I'll just wait until the pull request is accepted, then

**Comment by FlorentBecker** [comment]
What is the current status of this?

**Comment by diml** [comment]
113.33.00+4.03 builds with 4.03 and 4.04.
