### ISSUE TITLE
README out-of-date and links broken, ppx docs missing

### ISSUE THREAD

**Issue by dsheets** [janestreet/sexplib#19]
The README seems to be out-of-date and containing broken links to documentation. The `ppx_sexp_conv` repo README points here.

**Comment by diml** [comment]
We are currently updating a few READMEs. They'll be updated on github soon

**Comment by dsheets** [comment]
Great! Thanks! The obvious thing works anyway. :smile:

**Comment by hhugo** [comment]
@yminsky, I was not able to assign this to @jsomers

**Comment by yminsky** [comment]
Possible now. Had to adjust team membership. Looks like there's a single link that needs fixing.

**Comment by aalekseyev** [comment]
Looks like this was fixed.
