### ISSUE TITLE
broken with 4.02.3

### ISSUE THREAD

**Issue by vbmithr** [janestreet/sexplib#24]
```
# File "src/conv.ml", line 188, characters 35-56:
# Error: Unbound type constructor extension_constructor
# Command exited with code 2.
```

**Comment by diml** [comment]
Which version of sexplib?

**Comment by vbmithr** [comment]
On 18/07/2016 14:30, Jérémie Dimino wrote:
> Which version of sexplib?

114.01+04

-- 
Vincent

**Comment by diml** [comment]
it is only compatible with ocaml 4.03. I updated the version constraint in janestreet/opam-repository
