### ISSUE TITLE
Build failure: Error: Unbound type constructor extension_constructor

### ISSUE THREAD

**Issue by yurivict** [janestreet/sexplib#28]
These warnings and errors are printed during build on the FreeBSD:

```
          sh src/pre_sexp.pp.ml
src/pre_sexp.ml:62:42: warning: missing terminating ' character [-Winvalid-pp-token]
   is taken in account.  Under Unix there's no easy way to get the umask in
                                         ^
src/pre_sexp.ml:242:13: warning: missing terminating ' character [-Winvalid-pp-token]
  | Done of 't * Parse_pos.t
            ^
src/pre_sexp.ml:245:63: warning: missing terminating ' character [-Winvalid-pp-token]
and ('a, 't) parse_fun = pos : int -> len : int -> 'a -> ('a, 't) parse_result
                                                              ^
src/pre_sexp.ml:247:6: warning: missing terminating ' character [-Winvalid-pp-token]
type 't parse_state =
     ^
src/pre_sexp.ml:250:22: warning: missing terminating ' character [-Winvalid-pp-token]
    mutable pstack : 't;
                     ^
src/pre_sexp.ml:347:26: warning: missing terminating ' character [-Winvalid-pp-token]
     are non-empty, so it's incomplete parse anyway.
                         ^
src/pre_sexp.ml:948:57: warning: missing terminating ' character [-Winvalid-pp-token]
           "multiple S-expressions" branch, but it doesn't matter that much *)
                                                        ^
7 warnings generated.
      ocamlc src0/sexplib0__Sexp_conv.{cmi,cmti} (exit 2)
(cd _build/default && /usr/local/bin/ocamlc.opt -w -40 -g -bin-annot -no-alias-deps -I src0 -open Sexplib0 -o src0/sexplib0__Sexp_conv.cmi -c -intf src0/sexp_conv.mli)
File "src0/sexp_conv.mli", line 252, characters 32-53:
Error: Unbound type constructor extension_constructor
```

Version 0.9.1.

**Comment by diml** [comment]
This use of cpp on ml files is just too painful, we need to switch to cppo

**Comment by yurivict** [comment]
But how to make it to build?

**Comment by diml** [comment]
If you look in src/jbuild, there is `${PA_CPP} ${<}`, this is what calls cpp. You can try to replace `${PA_CPP}` by a call to cpp that works for this file

**Comment by yurivict** [comment]
I tried /usr/bin/cpp /usr/local/bin/clang-cpp40 (clang) /usr/local/bin/cpp6 (gcc) and they both don't work.

**Comment by diml** [comment]
Maybe there is some option to pass to make it work?

**Comment by yurivict** [comment]
Is anybody able to build it at all?

**Comment by diml** [comment]
Well, it's released in opam so it builds on all the systems tested by the opam CI infrastructure. I don't think FreeBSD is one of them though. /cc @avsm

**Comment by yurivict** [comment]
What is the version of cpp that it work with?

**Comment by yurivict** [comment]
I am trying to create FreeBSD ports for several ocaml packages, and got stuck with this problem.

Are you able to build it yourself? If yes, what does ```cpp --version``` command return?

**Comment by diml** [comment]
Yes, I'm able to build it myself. I have gcc 4.8.5

**Comment by yurivict** [comment]
After replacing of PA_CPP with /usr/local/bin/cpp48 from gcc-4.8.5 build still fails the same way.

**Comment by hhugo** [comment]
Since https://github.com/janestreet/sexplib/commit/e128a99caaac96d6aef6f957bfe09277dbb169a7 we no longer rely on CPP to build sexplib.
