### ISSUE TITLE
Compilation error on Windows

### ISSUE THREAD

**Issue by bcc32** [janestreet/sexplib#30]
I tried `opam install sexplib` using the `opam-repository-mingw` [installer](https://fdopen.github.io/opam-repository-mingw/installation/) and got the following compilation error:

```
$ opam install sexplib
The following actions will be performed:
  ∗  install sexplib v0.9.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[sexplib: sh winconfigure] Command started
[ERROR] The compilation of sexplib failed at "sh winconfigure".

#=== ERROR while compiling sexplib.v0.9.2 =====================================#
# opam-version         1.3.0~dev (2c2399d98ad0ebcb43a4bc856f3636030bb376db)
# os                   win32
# command              sh winconfigure
# path                 ~/.opam/4.05.0+mingw64c/build/sexplib.v0.9.2
# exit-code            2
# env-file             ~/.opam/4.05.0+mingw64c/build/sexplib.v0.9.2\sexplib-376-5f1023.env
# stdout-file          ~/.opam/4.05.0+mingw64c/build/sexplib.v0.9.2\sexplib-376-5f1023.out
# stderr-file          ~/.opam/4.05.0+mingw64c/build/sexplib.v0.9.2\sexplib-376-5f1023.err
### stderr ###
# winconfigure: line 2: $'\r': command not found
# winconfigure: line 4: $'\r': command not found
# winconfigure: line 5: syntax error near unexpected token `$'in\r''
' winconfigure: line 5: `case "$OS_SYSTEM" in



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  λ  build sexplib v0.9.2
No changes have been performed
```

The error messages suggest to me that the problem might be similar to the one discussed [here](http://www.dra27.uk/blog/platform/2017/08/24/merlin-3-on-windows.html#the-dreaded-r-pr682) and at ocaml/merlin#682.

**Comment by trefis** [comment]
winconfigure seems to come from [opam-repository-mingw](https://github.com/fdopen/opam-repository-mingw/blob/master/packages/sexplib/sexplib.v0.9.2/files/winconfigure) so I think you probably want to open the issue there as
- it might impact other packages of their repository
- they will be the most competent for fixing the actual issue

**Comment by bcc32** [comment]
Ah, ok. I wasn't quite sure since I was able to install a couple other packages successfully, including `stdio`, and I had no idea where `winconfigure` came from. I'll open the issue there.
