### ISSUE TITLE
sexplib requirement of ocaml-version >= "4.06.0" in opam

### ISSUE THREAD

**Issue by alrev** [janestreet/sexplib#32]
The new version of sexplib v.0.9.3 requires OCaml version at least 4.06.0 [(https://opam.ocaml.org/packages/sexplib/sexplib.v0.9.3/),](https://opam.ocaml.org/packages/sexplib/sexplib.v0.9.3/) and the new base v.0.9.4 requires sexplib v.0.9.3 [(https://opam.ocaml.org/packages/base/base.v0.9.4/),](https://opam.ocaml.org/packages/base/base.v0.9.4/) although the base has ocaml-version >= "4.03.0" requirement, and the base is part of other libraries (core and etc.).
Is it possible to have lower requirement for the new sexplib, for example ocaml-version >= "4.05.0" (or >= 4.03.0 as for the base)?

**Comment by xclerc** [comment]
After some testing, it seems to be fine to relax the lower bound to 4.04.2
(see https://github.com/ocaml/opam-repository/pull/10657)

**Comment by alrev** [comment]
Thank you, xclerc.

**Comment by alrev** [comment]
It seems the build fails for 4.04.2, but it is fine with 4.05.0. Maybe due to this change [https://github.com/ocaml/ocaml/pull/875](https://github.com/ocaml/ocaml/pull/875)?
4.05.0 as a lower bound would be fine as well.

**Comment by xclerc** [comment]
No, it is due to me performing the tests on the wrong branch...
The correct lower bound is indeed 4.05.0, I have just updated
the opam PR.
