### ISSUE TITLE
support for csexpr ?

### ISSUE THREAD

**Issue by abate** [janestreet/sexplib#33]
I want to parse a string of the form : "(10:public-key(3:rsa(1:n513:\000\195#n\248\227o0\183\252 ZN\1 ... "
that is encoded as a csexpr . It this possible with sexplib ? Would it be possible to add support for this kind of sexpr encoding ?

thanks !

**Comment by trefis** [comment]
Ping @xclerc .

**Comment by xclerc** [comment]
Sexplib seems to successfully parse the following OCaml string literal:
    "(10:public-key(3:rsa(1:n513:\000\195#n\248\227o0\183\252 ZN\001 ... )))"

Is the string you posted an OCaml literal?

**Comment by xclerc** [comment]
Looks like I misunderstood the question... I will have a look to
determine whether we could support canonical s-expressions.

**Comment by aalekseyev** [comment]
It looks like today you can use the [csexp](https://github.com/ocaml-dune/csexp) library to parse strings into `Sexp.t`.
I'm closing this issue because I think there is no need for a tighter integration here.
