### ISSUE TITLE
How to use sexplib?

### ISSUE THREAD

**Issue by cogumbreiro** [janestreet/sexplib#36]
Hi, everyone,

I am trying to learn how to use Sexplib. I am sorry if I'm missing the obvious, but I couldn't find a basic example of how to use the library in the README, nor could I find any link to documentation.

Is the source code the only source of documentation?

Thanks for your time.

**Comment by cogumbreiro** [comment]
Closing, as I meant to post this comment on parsexp and not sexplib. Sorry about the noise, everyone.

**Comment by cogumbreiro** [comment]
I've reopened because the point still stands.

I've added a pull request #38 to fix this issue.

**Comment by bcc32** [comment]
Fixed in #38, thanks for your contribution!

**Comment by cogumbreiro** [comment]
Thank you @bcc32 for the great software!
