### ISSUE TITLE
raw string literals in sexprs?

### ISSUE THREAD

**Issue by chetmurthy** [janestreet/sexplib#39]
It seems like it might be nice for sexplib to support parsing sexprs containing raw string literals, just as ocaml now supports that.  Would this be something you'd accept as a change in the syntax?  I figure I should check before I go do the hack (which is arguably pretty minuscule).

**Comment by diml** [comment]
I'm afraid that extending the syntax is not something we should do lightly. At least at Jane Street we have been using s-expressions for a long time and introducing a new extended syntax would inevitably cause some churn.

**Comment by chetmurthy** [comment]
Fair enough, I guess.  I'll just make one other attempt, and then drop it.

I'm not suggesting -printing- s-exps with raw-string-literals; rather, only -parsing- them.  This would be a new syntax for s-exps, so any existing s-exps that already parse, would continue to parse the same as before.

But sure, I can imagine that with a large enough codebase, it can become dangerous to make any changes other than those that seem truly necessary.

**Comment by chetmurthy** [comment]
Oh, I see you have another layer of s-expression parsing in janestreet/parsexp.  Hm, I think I can see why you want to leave that undisturbed.  Closing.
