### ISSUE TITLE
Trailing white space cannot be handled?

### ISSUE THREAD

**Issue by MassD** [janestreet/sexplib#8]
When I try sexplib, it tells me

`Sexp.of_string " a";;` is correct.

`Sexp.of_string "a ";;` is wrong.

---

Please see [In StackOverflow, Is trailing white space is forbidden in s-expression?](http://stackoverflow.com/questions/23682063/is-trailing-white-space-is-forbidden-in-s-expression/23702111?noredirect=1#23702111) for more details

**Comment by hhugo** [comment]
```
Sexp.of_string "a ";;
```
now works
